{% set name = "rubrix" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rubrix-{{ version }}.tar.gz
  sha256: 581c6d9f5cd3a8e4479535027e88d52b1eabbc1fe0ab199a9591137c46ddcfa3

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - python >=3.7
    - httpx >=0.15.0,<0.16.0
    - numpy
    - pandas >=1.0.0,<2.0.0
    - pydantic >=1.7.1
    - starlette >=0.13.0,<1.0.0
    - tqdm >=4.27.0
    - wrapt >=1.13.0,<1.14.0
    # server dependencies
    - fastapi >=0.63.0,<0.64.0
    - opensearch-py >=1.0.0,<1.1.0
    - uvicorn-standard >0.15.0,<0.18.0
    - smart-open
    - brotli-asgi >=1.1.0,<1.2.0
    - Deprecated >=1.2.0,<1.3.0
    - scikit-learn >=0.24.2
    - stopwordsiso >=0.6.1,<0.7.0
    - aiofiles >=0.6.0,<0.7.0
    - PyYAML >=5.4.1,<5.5.0
    - python-multipart >=0.0.5,<0.1.0
    - python-jose >=3.2.0,<3.3.0
    - passlib >=1.7.4,<1.8.0
    - hurry.filesize
    - psutil >=5.8.0,<5.9.0
    
test:
  imports:
    - rubrix
    - rubrix.client
    - rubrix.server.server
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://recogn.ai
  summary: Open-source tool for exploring, labeling, and monitoring data for NLP projects.
  license: Apache-2.0
  license_file: LICENSE
  description: |
    Rubrix is a **production-ready Python framework for exploring, annotating, and 
    managing data** in NLP projects.

    Key features:

      - **Open**: Rubrix is free, open-source, and 100% compatible with major NLP 
        libraries (Hugging Face transformers, spaCy, Stanford Stanza, Flair, etc.). 
        In fact, you can use and combine your preferred libraries without implementing 
        any specific interface.

      - **End-to-end**: Most annotation tools treat data collection as a one-off 
        activity at the beginning of each project. In real-world projects, data 
        collection is a key activity of the iterative process of ML model development. 
        Once a model goes into production, you want to monitor and analyze its 
        predictions, and collect more data to improve your model over time. Rubrix 
        is designed to close this gap, enabling you to iterate as much as you need.

      - **User and Developer Experience**: The key to sustainable NLP solutions is to 
        make it easier for everyone to contribute to projects. Domain experts should 
        feel comfortable interpreting and annotating data. Data scientists should feel 
        free to experiment and iterate. Engineers should feel in control of data 
        pipelines. Rubrix optimizes the experience for these core users to make your 
        teams more productive.

      - **Beyond hand-labeling**: Classical hand labeling workflows are costly and 
        inefficient, but having humans-in-the-loop is essential. Easily combine 
        hand-labeling with active learning, bulk-labeling, zero-shot models, and 
        weak-supervision in novel data annotation workflows.

    PyPI: [https://pypi.org/project/rubrix](https://pypi.org/project/rubrix)

  doc_url: https://rubrix.readthedocs.io/en/stable/
  dev_url: https://github.com/recognai/rubrix

extra:
  recipe-maintainers:
    - sugatoray
    # Maintainers from rubrix repository
    - dcfidalgo
